global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s
  external_labels:
    cluster: 'url-shortener-cluster'
    environment: 'production'
    project: 'devops-final'

rule_files:
  - "alerts.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    scrape_timeout: 15s
    metrics_path: '/metrics'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'prometheus-server'

  - job_name: 'url-shortener'
    static_configs:
      - targets: ['url-shortener-latest-gccb.onrender.com:443']
    scheme: https
    scrape_interval: 30s
    scrape_timeout: 15s
    metrics_path: '/metrics'
    params:
      format: ['prometheus']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'url-shortener-render-prod'
      - target_label: service
        replacement: 'url-shortener'
      - target_label: environment
        replacement: 'production'
      - target_label: deployment_type
        replacement: 'render'
      - target_label: team
        replacement: 'devops-team'

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 5s
    scrape_timeout: 5s
    metrics_path: '/metrics'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'docker-host'
      - target_label: service
        replacement: 'system-monitoring'

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: '/metrics'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'grafana-server'
      - target_label: service
        replacement: 'visualization'