name: CD Pipeline

concurrency:
  group: cd-pipeline-main
  cancel-in-progress: true

on:
  pull_request:
    types: [ closed ]
    branches: [ main ]
  workflow_dispatch:

jobs:
  cd:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push image
        uses: docker/build-push-action@v5
        with:
          context: ./app
          file: ./app/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/url-shortener:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/url-shortener:${{ github.sha }}