name: CI Pipeline

on:
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest
    
    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f app/requirements.txt ]; then
          pip install -r app/requirements.txt
        else
          pip install -r requirements.txt
        fi
        pip install flake8 black pytest

    - name: Lint with flake8
      run: |
        if [ -d app ]; then
          flake8 app/ --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 app/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        else
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        fi

    - name: Format check with black
      run: |
        if [ -d app ]; then
          black --check app/
        else
          black --check .
        fi

    - name: Run tests
      run: |

        export PYTHONPATH=$PYTHONPATH:.

        if [ -f app/tests/test_main.py ]; then
          pytest app/tests/ -v
        else
          pytest test_main.py -v
        fi

    - name: Build Docker image
      run: |
        if [ -f app/Dockerfile ]; then
          docker build -t url-shortener ./app
        else
          docker build -t url-shortener .
        fi